---
# Use your own keyfile location
# Variables for config
env: "local"

user: "asif"
http_url: "https://honeypot"
https_url: "https://honeypot"

home_folder: "/home/{{user}}"
honeypot_folder: "{{home_folder}}/honeypot"
www_folder: "/var/www/honeypot"
git_repo: "ssh://@git.ti.howest.be:TI/2022-2023/s3/websecurity-and-honeypot/students/group-03/honeypot.git"
key_file: "{{ home_folder }}/.ssh/id.ed25519"
http_conf: "honeypot.conf"
https_conf: "honeypot-ssl.conf"

# Passwords
database_password: "asiprolex2022"
# kibana_password: "asiprolex2022"

# elastic_super_user_password : AiX=Q+JwvJsgu=mxyrNN