# Config Laravel

- name: Laravel - Set up .env file
  template:
    src: "files/env.j2"
    dest: "{{honeypot_folder}}/.env"

# Composer
- name: Laravel - install Dependencies with Composer
  composer:
    command: update
    working_dir: "{{honeypot_folder}}"

# NPM
- name: Laravel - install Dependencies with NPM
  shell: npm install
  args:
    chdir: "{{honeypot_folder}}"

- name: Laravel - compile Dependencies with NPM
  shell: npm run dev
  args:
    chdir: "{{honeypot_folder}}"

- name: Laravel - compile Dependencies with NPM (TWICE)
  shell: npm run dev
  args:
    chdir: "{{honeypot_folder}}"

# Symlinks
- name: Laravel - Set up app storage link
  shell: /usr/bin/php {{honeypot_folder}}/artisan storage:link

# Groups
- name: Laravel - Ensure user is in group www-data
  shell: sudo usermod -aG www-data {{user}}

# Cache
- name: Laravel - Clear config cache
  shell: php artisan config:clear
  args:
    chdir: "{{ honeypot_folder }}"

- name: Laravel - Clear route cache
  shell: php artisan route:clear
  args:
    chdir: "{{ honeypot_folder }}"

- name: Laravel - Clear route cache
  shell: php artisan view:clear
  args:
    chdir: "{{ honeypot_folder }}"

# Permissions
- name: Laravel - Ensure storage is owned by www-data
  shell: sudo chown -R www-data:www-data {{honeypot_folder}}/storage

- name: Laravel - Ensure bootstrap/cache is owned by www-data
  shell: sudo chown -R www-data:www-data {{honeypot_folder}}/bootstrap/cache

- name: Laravel - Ensure storage is 775
  shell: sudo chmod -R 775 {{honeypot_folder}}/storage

- name: Laravel - Ensure bootstrap/cache is 775
  shell: sudo chmod -R 775 {{honeypot_folder}}/bootstrap/cache

# Migrations & Seeding
- name: Laravel - Do Migrations and Seeding
  shell: php artisan migrate:fresh --seed
  args:
    chdir: "{{honeypot_folder}}"

# Online
- name: Laravel - Put up
  shell: php artisan up
  args:
    chdir: "{{honeypot_folder}}"

# - name: Put under maintenance
#   shell: php artisan down --secret="catcatcat" --render="errors::503"
#   args:
#     chdir: "{ honeypot_folder }}"
