---
# before you start running playbooks
# In your VM run:
# ssh debian@honeypot
#   apt install -y sudo python3.9
#   usermod -aG sudo debian
#   mkdir .ssh
#   exit

# In your Host run
# nano /etc/hosts
# nano /etc/ansible/hosts
# scp ~/.ssh/id* debian@honeypot:/home/debian/.ssh
# ansible-playbook honeypot.yml -u debian --ask-pass -b -K

- name: Honeypot Setup
  hosts: honeypot
  become: true
  vars_files:
    - vars/local.yml
  tasks:
    - include_tasks: tasks/install.yml
    - include_tasks: tasks/config.yml 
    - include_tasks: tasks/apache2.yml
    - include_tasks: tasks/mysql.yml
    # - include_tasks: tasks/laravel.yml
    # - include_tasks: tasks/elastic.yml

  handlers:
   - name: Reload Apache
     service:
       name: apache2
       state: reloaded

   - name: Restart Apache
     service:
       name: apache2
       state: restarted