---

- name: Honeypot Setup
  hosts: honeypot
  become: true
  vars_files:
    - vars/local.yml
  tasks:
    - include_tasks: tasks/install.yml
    - include_tasks: tasks/config.yml 
    - include_tasks: tasks/elastic.yml
